version: "3.7"
services:
  app:
    build:
      args:
        user: venus
        uid: 1000
      context: ./
      dockerfile: ./php/Dockerfile
    image: lnu-internship
    container_name: lnu-internship-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lnu-internship

  db:
   image: mysql:5.7
   container_name: lnu-internship-db
   restart: unless-stopped
   environment:
     MYSQL_DATABASE: ${DB_DATABASE}
     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
     MYSQL_PASSWORD: ${DB_PASSWORD}
     MYSQL_USERNAME: ${DB_USERNAME}
     SERVICE_TAGS: dev
     SERVICE_NAME: mysql
   volumes:
     - ./docker-compose/mysql:/docker-entrypoint-initdb.d
   networks:
     - lnu-internship

  nginx:
   image: nginx:alpine
   container_name: lnu-internship-nginx
   restart: unless-stopped
   ports:
     - 8000:80
   volumes:
     - ./:/var/www
     - ./docker-compose/nginx:/etc/nginx/conf.d/
   networks:
     - lnu-internship

networks:
  lnu-internship:
    driver: bridge
